INSERT INTO Account(ID, customer_id, Balance) VALUES ('82711', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 29937);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('72619', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 44556);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('80208', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 97108);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('48264', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 81089);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('43386', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 5722);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('13467', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 89868);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('22586', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 66179);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('81319', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 6074);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('01180', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 78488);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('06698', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 24355);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('51873', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 17196);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('42891', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 87057);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('99225', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 56517);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('04203', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 38940);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('99352', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 27847);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('65058', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 22066);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('50996', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 54336);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('51542', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 95957);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('92006', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 5677);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('56046', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 12935);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('82685', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 2980);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('06034', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 48011);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('63120', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 10876);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('49158', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 62519);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('80668', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 5584);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('18884', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 69177);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('41811', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 62837);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('44018', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 16606);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('35712', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 74222);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('98817', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 52101);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('24700', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 6118);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('97724', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 33660);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('83462', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 93556);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('29516', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 29690);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('00322', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 37861);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('82093', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 4105);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('04186', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 84589);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('10341', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 86552);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('13136', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 38300);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('71597', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 63100);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('34729', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 81669);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('45576', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 29909);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('87160', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 25445);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('94618', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 51697);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('60903', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 96652);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('24287', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 36284);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('92312', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 33225);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('13384', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 87549);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('69311', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 96752);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('66858', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 46374);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('59370', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 48223);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('65436', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 91577);
INSERT INTO Account(ID, customer_id, Balance) VALUES ('91823', (SELECT ID FROM Customer ORDER BY DBMS_RANDOM.VALUE FETCH FIRST 1 ROW ONLY), 75777);


CREATE SEQUENCE transaction_seq 
START WITH 1 
INCREMENT BY 1 
NOCACHE;

INSERT INTO Account(ID, customer, Balance) 
VALUES (LPAD(account_seq.NEXTVAL, 5, '0'), '04049', 48223);

INSERT INTO Account(ID, customer, Balance) 
VALUES (LPAD(account_seq.NEXTVAL, 5, '0'), '04049', 22343);

INSERT INTO Account(ID, customer, Balance) 
VALUES (LPAD(account_seq.NEXTVAL, 5, '0'), '04049', 6790);

describe savings_account;

select * from transaction;
